// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_benchScreen.h"
#include "screens/ui_mainScreen.h"
#include "screens/ui_settingsScreen.h"
//#include "screens/ui_engineConfigScreen.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_FontIndicator);
LV_FONT_DECLARE(ui_font_FontIndicatorLabel);
LV_FONT_DECLARE(ui_font_FontLabel);
LV_FONT_DECLARE(ui_font_FontRPM);
LV_FONT_DECLARE(ui_font_FontSpeed);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
