// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void upBrightness(lv_event_t * e);
void downBribrightness(lv_event_t * e);
void preInitSettingsScreen(lv_event_t * e);
void benchScreenInitSetup(lv_event_t * e);
void benchIGN1(lv_event_t * e);
void benchIGN2(lv_event_t * e);
void benchIGN3(lv_event_t * e);
void benchIGN4(lv_event_t * e);
void benchIGN5(lv_event_t * e);
void benchIGN6(lv_event_t * e);
void benchIGN7(lv_event_t * e);
void benchIGN8(lv_event_t * e);
void benchINJ1(lv_event_t * e);
void benchINJ2(lv_event_t * e);
void benchINJ3(lv_event_t * e);
void benchINJ4(lv_event_t * e);
void benchINJ5(lv_event_t * e);
void benchINJ6(lv_event_t * e);
void benchINJ7(lv_event_t * e);
void benchINJ8(lv_event_t * e);
void StartStop(lv_event_t * e);
void benchFuelPump(lv_event_t * e);
void benchFan2(lv_event_t * e);
void benchFan1(lv_event_t * e);
void rpmWarnSetPlus(lv_event_t * e);
void rpmWarnSetMinus(lv_event_t * e);
void cltWarnSetPlus(lv_event_t * e);
void cltWarnSetMinus(lv_event_t * e);
void iatWarnSetPlus(lv_event_t * e);
void iatWarnSetMinus(lv_event_t * e);
void oilTWarnSetPlus(lv_event_t * e);
void oilTWarnSetMinus(lv_event_t * e);
void oilPWarnSetPlus(lv_event_t * e);
void oilPWarnSetMinus(lv_event_t * e);
void fuelPWarnSetPlus(lv_event_t * e);
void fuelPWarnSetMinus(lv_event_t * e);
void vBattWarnSetPlus(lv_event_t * e);
void vBattWarnSetMinus(lv_event_t * e);
void setIsTurbo(lv_event_t * e);
void setIsNaturalA(lv_event_t * e);
void saveWarnSet(lv_event_t * e);
void defaultWarnSet(lv_event_t * e);
void engineSettingScreenInitSettup(lv_event_t * e);
void engSetSave(lv_event_t * e);
void setDisp48L(lv_event_t * e);
void setDisp53L(lv_event_t * e);
void setDisp57L(lv_event_t * e);
void setDisp60L(lv_event_t * e);
void setDisp62L(lv_event_t * e);
void setDisp70L(lv_event_t * e);
void setTrig24(lv_event_t * e);
void setTrig58(lv_event_t * e);
void setCamS1(lv_event_t * e);
void setCamS2(lv_event_t * e);
void setCamS4(lv_event_t * e);
void clearEngConfiguration(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
