// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void upBrightness(lv_event_t * e);
void downBribrightness(lv_event_t * e);
void rpmWarnSetPlus(lv_event_t * e);
void rpmWarnSetMinus(lv_event_t * e);
void cltWarnSetPlus(lv_event_t * e);
void cltWarnSetMinus(lv_event_t * e);
void iatWarnSetPlus(lv_event_t * e);
void iatWarnSetMinus(lv_event_t * e);
void oilTWarnSetPlus(lv_event_t * e);
void oilTWarnSetMinus(lv_event_t * e);
void oilPWarnSetPlus(lv_event_t * e);
void oilPWarnSetMinus(lv_event_t * e);
void fuelPWarnSetPlus(lv_event_t * e);
void fuelPWarnSetMinus(lv_event_t * e);
void vBattWarnSetPlus(lv_event_t * e);
void vBattWarnSetMinus(lv_event_t * e);
void saveWarnSet(lv_event_t * e);
void defaultWanSet(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
