// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"

#define LV_LABEL_LONG_MODE_CLIP LV_LABEL_LONG_CLIP

lv_obj_t * ui_mainScreen = NULL;
lv_obj_t * ui_rpmBar0 = NULL;
lv_obj_t * ui_rpmVal0 = NULL;
lv_obj_t * ui_rpmLabel1 = NULL;
lv_obj_t * ui_speedVal0 = NULL;
lv_obj_t * ui_speedLabel1 = NULL;
lv_obj_t * ui_afrBar0 = NULL;
lv_obj_t * ui_afrVal0 = NULL;
lv_obj_t * ui_cltBar0 = NULL;
lv_obj_t * ui_cltVal0 = NULL;
lv_obj_t * ui_iatBar0 = NULL;
lv_obj_t * ui_iatVal0 = NULL;
lv_obj_t * ui_vBattLabel1 = NULL;
lv_obj_t * ui_vBattVal0 = NULL;
lv_obj_t * ui_mapBar0 = NULL;
lv_obj_t * ui_mapVal0 = NULL;
lv_obj_t * ui_oilPressBar0 = NULL;
lv_obj_t * ui_oilPressVal0 = NULL;
lv_obj_t * ui_fuelPressBar0 = NULL;
lv_obj_t * ui_fuelPressVal0 = NULL;
lv_obj_t * ui_fuelLevelBar0 = NULL;
lv_obj_t * ui_fuelLevelVal0 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_cltLabel1 = NULL;
lv_obj_t * ui_iatLabel1 = NULL;
lv_obj_t * ui_oilTempLabel1 = NULL;
lv_obj_t * ui_oilTempBar0 = NULL;
lv_obj_t * ui_oilTempVal1 = NULL;
lv_obj_t * ui_oilPressLabel1 = NULL;
lv_obj_t * ui_fuelPressLabel1 = NULL;
lv_obj_t * ui_fuelLevelLabel1 = NULL;
lv_obj_t * ui_afrLabel1 = NULL;
lv_obj_t * ui_mapLabel1 = NULL;
lv_obj_t * ui_LabelClt40 = NULL;
lv_obj_t * ui_LabelClt80 = NULL;
lv_obj_t * ui_LabelClt120 = NULL;
lv_obj_t * ui_LabelIat0 = NULL;
lv_obj_t * ui_LabelIat40 = NULL;
lv_obj_t * ui_LabelIat80 = NULL;
lv_obj_t * ui_LabelOilTemp120 = NULL;
lv_obj_t * ui_LabelOilTemp40 = NULL;
lv_obj_t * ui_LabelOilTemp80 = NULL;
lv_obj_t * ui_LabelAfr10 = NULL;
lv_obj_t * ui_LabelAfr15 = NULL;
lv_obj_t * ui_LabelAfr20 = NULL;
lv_obj_t * ui_LabelMap100 = NULL;
lv_obj_t * ui_LabelMap50 = NULL;
lv_obj_t * ui_LabelMap0 = NULL;
lv_obj_t * ui_LabelOil0 = NULL;
lv_obj_t * ui_LabelOil25 = NULL;
lv_obj_t * ui_LabelOil5 = NULL;
lv_obj_t * ui_LabelFuelP1 = NULL;
lv_obj_t * ui_LabelFuelP3 = NULL;
lv_obj_t * ui_LabelFuelP5 = NULL;
lv_obj_t * ui_LabelFuelLevelF = NULL;
lv_obj_t * ui_LabelFuelLevelH = NULL;
lv_obj_t * ui_LabelFuelLevelE = NULL;
// event funtions
void ui_event_mainScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_active());
        upBrightness(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_active());
        downBribrightness(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_delete(&ui_mainScreen_screen_destroy);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_settingsScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_settingsScreen_screen_init);
        _ui_screen_delete(&ui_mainScreen_screen_destroy);
    }
}

// build funtions

void ui_mainScreen_screen_init(void)
{
    ui_mainScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_mainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainScreen, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmBar0 = lv_bar_create(ui_mainScreen);
    lv_bar_set_range(ui_rpmBar0, 0, 800);
    lv_obj_set_width(ui_rpmBar0, 800);
    lv_obj_set_height(ui_rpmBar0, 80);
    lv_obj_set_style_radius(ui_rpmBar0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rpmBar0, lv_color_hex(0x393839), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rpmBar0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_rpmBar0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_rpmBar0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_rpmBar0, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_rpmBar0, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_rpmBar0, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rpmBar0, lv_color_hex(0xE0FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rpmBar0, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_rpmBar0, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_rpmBar0,
                                                                                              lv_obj_get_style_pad_right(ui_rpmBar0, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_rpmVal0 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_rpmVal0, 100);
    lv_obj_set_height(ui_rpmVal0, 16);
    lv_obj_set_x(ui_rpmVal0, -10);
    lv_obj_set_y(ui_rpmVal0, 37);
    lv_obj_set_align(ui_rpmVal0, LV_ALIGN_TOP_RIGHT);
    lv_label_set_long_mode(ui_rpmVal0, LV_LABEL_LONG_MODE_CLIP);
    lv_label_set_text(ui_rpmVal0, "0");
    lv_obj_set_style_text_color(ui_rpmVal0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rpmVal0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_rpmVal0, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rpmVal0, &ui_font_FontRPM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_rpmVal0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_rpmVal0, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_rpmVal0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_rpmVal0, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmLabel1 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_rpmLabel1, 60);
    lv_obj_set_height(ui_rpmLabel1, 14);
    lv_obj_set_x(ui_rpmLabel1, -17);
    lv_obj_set_y(ui_rpmLabel1, 54);
    lv_obj_set_align(ui_rpmLabel1, LV_ALIGN_TOP_RIGHT);
    lv_label_set_long_mode(ui_rpmLabel1, LV_LABEL_LONG_MODE_CLIP);
    lv_label_set_text(ui_rpmLabel1, "rpm");
    lv_obj_set_style_text_color(ui_rpmLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rpmLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_rpmLabel1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rpmLabel1, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_rpmLabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_rpmLabel1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_rpmLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_rpmLabel1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speedVal0 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_speedVal0, 460);
    lv_obj_set_height(ui_speedVal0, 86);
    lv_obj_set_x(ui_speedVal0, -68);
    lv_obj_set_y(ui_speedVal0, -50);
    lv_obj_set_align(ui_speedVal0, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_speedVal0, LV_LABEL_LONG_MODE_CLIP);
    lv_label_set_text(ui_speedVal0, "0");
    lv_obj_set_style_text_color(ui_speedVal0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speedVal0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_speedVal0, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speedVal0, &ui_font_FontSpeed, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_speedVal0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_speedVal0, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_speedVal0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_speedVal0, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speedLabel1 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_speedLabel1, 60);
    lv_obj_set_height(ui_speedLabel1, 16);
    lv_obj_set_x(ui_speedLabel1, 226);
    lv_obj_set_y(ui_speedLabel1, -71);
    lv_obj_set_align(ui_speedLabel1, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_speedLabel1, LV_LABEL_LONG_MODE_CLIP);
    lv_label_set_text(ui_speedLabel1, "km/h");
    lv_obj_set_style_text_color(ui_speedLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speedLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_speedLabel1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speedLabel1, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_speedLabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_speedLabel1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_speedLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_speedLabel1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_afrBar0 = lv_bar_create(ui_mainScreen);
    lv_bar_set_mode(ui_afrBar0, LV_BAR_MODE_SYMMETRICAL);
    lv_bar_set_range(ui_afrBar0, -50, 50);
    lv_bar_set_value(ui_afrBar0, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_afrBar0, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_afrBar0, 200);
    lv_obj_set_height(ui_afrBar0, 35);
    lv_obj_set_x(ui_afrBar0, 300);
    lv_obj_set_y(ui_afrBar0, 306);
    lv_obj_set_style_radius(ui_afrBar0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_afrBar0, lv_color_hex(0x313031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_afrBar0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_afrBar0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_afrBar0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_afrBar0, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_afrBar0, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_afrBar0, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_afrBar0, lv_color_hex(0x00FFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_afrBar0, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_afrBar0, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_afrBar0,
                                                                                              lv_obj_get_style_pad_right(ui_afrBar0, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_afrVal0 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_afrVal0, 65);
    lv_obj_set_height(ui_afrVal0, 16);
    lv_obj_set_x(ui_afrVal0, 432);
    lv_obj_set_y(ui_afrVal0, 290);
    lv_label_set_long_mode(ui_afrVal0, LV_LABEL_LONG_MODE_CLIP);
    lv_label_set_text(ui_afrVal0, "20.0");
    lv_obj_set_style_text_color(ui_afrVal0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_afrVal0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_afrVal0, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_afrVal0, &ui_font_FontIndicator, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cltBar0 = lv_bar_create(ui_mainScreen);
    lv_bar_set_range(ui_cltBar0, 40, 120);
    lv_bar_set_start_value(ui_cltBar0, 40, LV_ANIM_OFF);
    lv_obj_set_width(ui_cltBar0, 200);
    lv_obj_set_height(ui_cltBar0, 35);
    lv_obj_set_x(ui_cltBar0, 17);
    lv_obj_set_y(ui_cltBar0, 266);
    lv_obj_set_style_radius(ui_cltBar0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cltBar0, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cltBar0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_cltBar0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_cltBar0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_cltBar0, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_cltBar0, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_cltBar0, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cltBar0, lv_color_hex(0xE6FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cltBar0, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_cltBar0, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_cltBar0,
                                                                                              lv_obj_get_style_pad_right(ui_cltBar0, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_cltVal0 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_cltVal0, 55);
    lv_obj_set_height(ui_cltVal0, 16);
    lv_obj_set_x(ui_cltVal0, 160);
    lv_obj_set_y(ui_cltVal0, 250);
    lv_label_set_long_mode(ui_cltVal0, LV_LABEL_LONG_MODE_CLIP);
    lv_label_set_text(ui_cltVal0, "-40");
    lv_obj_set_style_text_color(ui_cltVal0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cltVal0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cltVal0, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cltVal0, &ui_font_FontIndicator, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iatBar0 = lv_bar_create(ui_mainScreen);
    lv_bar_set_range(ui_iatBar0, 0, 80);
    lv_obj_set_width(ui_iatBar0, 200);
    lv_obj_set_height(ui_iatBar0, 35);
    lv_obj_set_x(ui_iatBar0, 17);
    lv_obj_set_y(ui_iatBar0, 346);
    lv_obj_set_style_radius(ui_iatBar0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_iatBar0, lv_color_hex(0x313031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_iatBar0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_iatBar0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_iatBar0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_iatBar0, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_iatBar0, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_iatBar0, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_iatBar0, lv_color_hex(0xE6FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_iatBar0, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_iatBar0, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_iatBar0,
                                                                                              lv_obj_get_style_pad_right(ui_iatBar0, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_iatVal0 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_iatVal0, 55);
    lv_obj_set_height(ui_iatVal0, 16);
    lv_obj_set_x(ui_iatVal0, 160);
    lv_obj_set_y(ui_iatVal0, 330);
    lv_label_set_long_mode(ui_iatVal0, LV_LABEL_LONG_MODE_CLIP);
    lv_label_set_text(ui_iatVal0, "-40");
    lv_obj_set_style_text_color(ui_iatVal0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_iatVal0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_iatVal0, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_iatVal0, &ui_font_FontIndicator, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vBattLabel1 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_vBattLabel1, 77);
    lv_obj_set_height(ui_vBattLabel1, 16);
    lv_obj_set_x(ui_vBattLabel1, -65);
    lv_obj_set_y(ui_vBattLabel1, 215);
    lv_obj_set_align(ui_vBattLabel1, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_vBattLabel1, LV_LABEL_LONG_MODE_CLIP);
    lv_label_set_text(ui_vBattLabel1, "vbatt");
    lv_obj_set_style_text_color(ui_vBattLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_vBattLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_vBattLabel1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_vBattLabel1, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_vBattLabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_vBattLabel1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_vBattLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_vBattLabel1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vBattVal0 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_vBattVal0, 65);
    lv_obj_set_height(ui_vBattVal0, 16);
    lv_obj_set_x(ui_vBattVal0, 432);
    lv_obj_set_y(ui_vBattVal0, 450);
    lv_label_set_long_mode(ui_vBattVal0, LV_LABEL_LONG_MODE_CLIP);
    lv_label_set_text(ui_vBattVal0, "0.0");
    lv_obj_set_style_text_color(ui_vBattVal0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_vBattVal0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_vBattVal0, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_vBattVal0, &ui_font_FontIndicator, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mapBar0 = lv_bar_create(ui_mainScreen);
    lv_bar_set_value(ui_mapBar0, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_mapBar0, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_mapBar0, 200);
    lv_obj_set_height(ui_mapBar0, 35);
    lv_obj_set_x(ui_mapBar0, 300);
    lv_obj_set_y(ui_mapBar0, 386);
    lv_obj_set_style_radius(ui_mapBar0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mapBar0, lv_color_hex(0x313031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mapBar0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_mapBar0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_mapBar0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_mapBar0, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_mapBar0, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_mapBar0, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mapBar0, lv_color_hex(0x01FF71), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mapBar0, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_mapBar0, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_mapBar0,
                                                                                              lv_obj_get_style_pad_right(ui_mapBar0, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_mapVal0 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_mapVal0, 65);
    lv_obj_set_height(ui_mapVal0, 16);
    lv_obj_set_x(ui_mapVal0, 432);
    lv_obj_set_y(ui_mapVal0, 370);
    lv_label_set_long_mode(ui_mapVal0, LV_LABEL_LONG_MODE_CLIP);
    lv_label_set_text(ui_mapVal0, "100");
    lv_obj_set_style_text_color(ui_mapVal0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mapVal0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_mapVal0, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mapVal0, &ui_font_FontIndicator, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_oilPressBar0 = lv_bar_create(ui_mainScreen);
    lv_bar_set_range(ui_oilPressBar0, 0, 500);
    lv_obj_set_width(ui_oilPressBar0, 200);
    lv_obj_set_height(ui_oilPressBar0, 35);
    lv_obj_set_x(ui_oilPressBar0, 583);
    lv_obj_set_y(ui_oilPressBar0, 266);
    lv_obj_set_style_radius(ui_oilPressBar0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_oilPressBar0, lv_color_hex(0x313031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_oilPressBar0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_oilPressBar0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_oilPressBar0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_oilPressBar0, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_oilPressBar0, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_oilPressBar0, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_oilPressBar0, lv_color_hex(0xE6FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_oilPressBar0, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_oilPressBar0, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_oilPressBar0,
                                                                                                   lv_obj_get_style_pad_right(ui_oilPressBar0, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_oilPressVal0 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_oilPressVal0, 55);
    lv_obj_set_height(ui_oilPressVal0, 16);
    lv_obj_set_x(ui_oilPressVal0, 726);
    lv_obj_set_y(ui_oilPressVal0, 250);
    lv_label_set_long_mode(ui_oilPressVal0, LV_LABEL_LONG_MODE_CLIP);
    lv_label_set_text(ui_oilPressVal0, "0.0");
    lv_obj_set_style_text_color(ui_oilPressVal0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_oilPressVal0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_oilPressVal0, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_oilPressVal0, &ui_font_FontIndicator, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fuelPressBar0 = lv_bar_create(ui_mainScreen);
    lv_bar_set_range(ui_fuelPressBar0, 100, 500);
    lv_bar_set_start_value(ui_fuelPressBar0, 100, LV_ANIM_OFF);
    lv_obj_set_width(ui_fuelPressBar0, 200);
    lv_obj_set_height(ui_fuelPressBar0, 35);
    lv_obj_set_x(ui_fuelPressBar0, 583);
    lv_obj_set_y(ui_fuelPressBar0, 346);
    lv_obj_set_style_radius(ui_fuelPressBar0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fuelPressBar0, lv_color_hex(0x313031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fuelPressBar0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_fuelPressBar0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_fuelPressBar0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_fuelPressBar0, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_fuelPressBar0, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_fuelPressBar0, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fuelPressBar0, lv_color_hex(0xE6FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fuelPressBar0, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_fuelPressBar0, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_fuelPressBar0,
                                                                                                    lv_obj_get_style_pad_right(ui_fuelPressBar0, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_fuelPressVal0 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_fuelPressVal0, 55);
    lv_obj_set_height(ui_fuelPressVal0, 16);
    lv_obj_set_x(ui_fuelPressVal0, 726);
    lv_obj_set_y(ui_fuelPressVal0, 330);
    lv_label_set_long_mode(ui_fuelPressVal0, LV_LABEL_LONG_MODE_CLIP);
    lv_label_set_text(ui_fuelPressVal0, "0.0");
    lv_obj_set_style_text_color(ui_fuelPressVal0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fuelPressVal0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_fuelPressVal0, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_fuelPressVal0, &ui_font_FontIndicator, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fuelLevelBar0 = lv_bar_create(ui_mainScreen);
    lv_obj_set_width(ui_fuelLevelBar0, 200);
    lv_obj_set_height(ui_fuelLevelBar0, 35);
    lv_obj_set_x(ui_fuelLevelBar0, 583);
    lv_obj_set_y(ui_fuelLevelBar0, 426);
    lv_obj_set_style_radius(ui_fuelLevelBar0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fuelLevelBar0, lv_color_hex(0x313031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fuelLevelBar0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_fuelLevelBar0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_fuelLevelBar0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_fuelLevelBar0, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_fuelLevelBar0, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_fuelLevelBar0, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fuelLevelBar0, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fuelLevelBar0, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_fuelLevelBar0, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_fuelLevelBar0,
                                                                                                    lv_obj_get_style_pad_right(ui_fuelLevelBar0, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_fuelLevelVal0 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_fuelLevelVal0, 55);
    lv_obj_set_height(ui_fuelLevelVal0, 16);
    lv_obj_set_x(ui_fuelLevelVal0, 726);
    lv_obj_set_y(ui_fuelLevelVal0, 409);
    lv_label_set_long_mode(ui_fuelLevelVal0, LV_LABEL_LONG_MODE_CLIP);
    lv_label_set_text(ui_fuelLevelVal0, "0");
    lv_obj_set_style_text_color(ui_fuelLevelVal0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fuelLevelVal0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_fuelLevelVal0, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_fuelLevelVal0, &ui_font_FontIndicator, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 82);
    lv_obj_set_y(ui_Label1, 94);
    lv_label_set_text(ui_Label1, "1");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_FontRPM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 174);
    lv_obj_set_y(ui_Label2, 94);
    lv_label_set_text(ui_Label2, "2");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_FontRPM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 276);
    lv_obj_set_y(ui_Label3, 94);
    lv_label_set_text(ui_Label3, "3");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_FontRPM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 375);
    lv_obj_set_y(ui_Label4, 94);
    lv_label_set_text(ui_Label4, "4");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_FontRPM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 474);
    lv_obj_set_y(ui_Label5, 94);
    lv_label_set_text(ui_Label5, "5");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_FontRPM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 574);
    lv_obj_set_y(ui_Label6, 94);
    lv_label_set_text(ui_Label6, "6");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_FontRPM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 675);
    lv_obj_set_y(ui_Label7, 94);
    lv_label_set_text(ui_Label7, "7");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_FontRPM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cltLabel1 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_cltLabel1, 60);
    lv_obj_set_height(ui_cltLabel1, 16);
    lv_obj_set_x(ui_cltLabel1, 16);
    lv_obj_set_y(ui_cltLabel1, 245);
    lv_label_set_long_mode(ui_cltLabel1, LV_LABEL_LONG_MODE_CLIP);
    lv_label_set_text(ui_cltLabel1, "clt");
    lv_obj_set_style_text_color(ui_cltLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cltLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cltLabel1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cltLabel1, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_cltLabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_cltLabel1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_cltLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_cltLabel1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iatLabel1 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_iatLabel1, 60);
    lv_obj_set_height(ui_iatLabel1, 16);
    lv_obj_set_x(ui_iatLabel1, 16);
    lv_obj_set_y(ui_iatLabel1, 325);
    lv_label_set_long_mode(ui_iatLabel1, LV_LABEL_LONG_MODE_CLIP);
    lv_label_set_text(ui_iatLabel1, "iat");
    lv_obj_set_style_text_color(ui_iatLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_iatLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_iatLabel1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_iatLabel1, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_iatLabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_iatLabel1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_iatLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_iatLabel1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_oilTempLabel1 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_oilTempLabel1, 70);
    lv_obj_set_height(ui_oilTempLabel1, 16);
    lv_obj_set_x(ui_oilTempLabel1, 16);
    lv_obj_set_y(ui_oilTempLabel1, 405);
    lv_label_set_long_mode(ui_oilTempLabel1, LV_LABEL_LONG_MODE_CLIP);
    lv_label_set_text(ui_oilTempLabel1, "oil t");
    lv_obj_set_style_text_color(ui_oilTempLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_oilTempLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_oilTempLabel1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_oilTempLabel1, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_oilTempLabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_oilTempLabel1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_oilTempLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_oilTempLabel1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_oilTempBar0 = lv_bar_create(ui_mainScreen);
    lv_bar_set_range(ui_oilTempBar0, 40, 120);
    lv_bar_set_start_value(ui_oilTempBar0, 40, LV_ANIM_OFF);
    lv_obj_set_width(ui_oilTempBar0, 200);
    lv_obj_set_height(ui_oilTempBar0, 35);
    lv_obj_set_x(ui_oilTempBar0, 17);
    lv_obj_set_y(ui_oilTempBar0, 426);
    lv_obj_set_style_radius(ui_oilTempBar0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_oilTempBar0, lv_color_hex(0x313031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_oilTempBar0, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_oilTempBar0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_oilTempBar0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_oilTempBar0, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_oilTempBar0, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_oilTempBar0, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_oilTempBar0, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_oilTempBar0, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_oilTempBar0, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_oilTempBar0,
                                                                                                  lv_obj_get_style_pad_right(ui_oilTempBar0, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_oilTempVal1 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_oilTempVal1, 55);
    lv_obj_set_height(ui_oilTempVal1, 16);
    lv_obj_set_x(ui_oilTempVal1, 160);
    lv_obj_set_y(ui_oilTempVal1, 409);
    lv_label_set_long_mode(ui_oilTempVal1, LV_LABEL_LONG_MODE_CLIP);
    lv_label_set_text(ui_oilTempVal1, "-40");
    lv_obj_set_style_text_color(ui_oilTempVal1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_oilTempVal1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_oilTempVal1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_oilTempVal1, &ui_font_FontIndicator, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_oilPressLabel1 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_oilPressLabel1, 60);
    lv_obj_set_height(ui_oilPressLabel1, 16);
    lv_obj_set_x(ui_oilPressLabel1, 582);
    lv_obj_set_y(ui_oilPressLabel1, 245);
    lv_label_set_long_mode(ui_oilPressLabel1, LV_LABEL_LONG_MODE_CLIP);
    lv_label_set_text(ui_oilPressLabel1, "oil p");
    lv_obj_set_style_text_color(ui_oilPressLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_oilPressLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_oilPressLabel1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_oilPressLabel1, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_oilPressLabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_oilPressLabel1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_oilPressLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_oilPressLabel1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fuelPressLabel1 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_fuelPressLabel1, 75);
    lv_obj_set_height(ui_fuelPressLabel1, 16);
    lv_obj_set_x(ui_fuelPressLabel1, 582);
    lv_obj_set_y(ui_fuelPressLabel1, 325);
    lv_label_set_long_mode(ui_fuelPressLabel1, LV_LABEL_LONG_MODE_CLIP);
    lv_label_set_text(ui_fuelPressLabel1, "fuel p");
    lv_obj_set_style_text_color(ui_fuelPressLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fuelPressLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_fuelPressLabel1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_fuelPressLabel1, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_fuelPressLabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_fuelPressLabel1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_fuelPressLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_fuelPressLabel1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fuelLevelLabel1 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_fuelLevelLabel1, 72);
    lv_obj_set_height(ui_fuelLevelLabel1, 16);
    lv_obj_set_x(ui_fuelLevelLabel1, 582);
    lv_obj_set_y(ui_fuelLevelLabel1, 405);
    lv_label_set_long_mode(ui_fuelLevelLabel1, LV_LABEL_LONG_MODE_CLIP);
    lv_label_set_text(ui_fuelLevelLabel1, "fuel l");
    lv_obj_set_style_text_color(ui_fuelLevelLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fuelLevelLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_fuelLevelLabel1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_fuelLevelLabel1, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_fuelLevelLabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_fuelLevelLabel1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_fuelLevelLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_fuelLevelLabel1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_afrLabel1 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_afrLabel1, 46);
    lv_obj_set_height(ui_afrLabel1, 16);
    lv_obj_set_x(ui_afrLabel1, -77);
    lv_obj_set_y(ui_afrLabel1, 53);
    lv_obj_set_align(ui_afrLabel1, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_afrLabel1, LV_LABEL_LONG_MODE_CLIP);
    lv_label_set_text(ui_afrLabel1, "afr");
    lv_obj_set_style_text_color(ui_afrLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_afrLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_afrLabel1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_afrLabel1, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_afrLabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_afrLabel1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_afrLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_afrLabel1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mapLabel1 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_mapLabel1, 46);
    lv_obj_set_height(ui_mapLabel1, 16);
    lv_obj_set_x(ui_mapLabel1, -77);
    lv_obj_set_y(ui_mapLabel1, 134);
    lv_obj_set_align(ui_mapLabel1, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_mapLabel1, LV_LABEL_LONG_MODE_CLIP);
    lv_label_set_text(ui_mapLabel1, "map");
    lv_obj_set_style_text_color(ui_mapLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mapLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_mapLabel1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mapLabel1, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_mapLabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_mapLabel1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_mapLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_mapLabel1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelClt40 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_LabelClt40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelClt40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelClt40, 17);
    lv_obj_set_y(ui_LabelClt40, 68);
    lv_obj_set_align(ui_LabelClt40, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelClt40, "40");
    lv_obj_set_style_text_color(ui_LabelClt40, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelClt40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelClt40, &ui_font_FontIndicatorLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelClt80 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_LabelClt80, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelClt80, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelClt80, 107);
    lv_obj_set_y(ui_LabelClt80, 68);
    lv_obj_set_align(ui_LabelClt80, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelClt80, "80");
    lv_obj_set_style_text_color(ui_LabelClt80, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelClt80, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelClt80, &ui_font_FontIndicatorLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelClt120 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_LabelClt120, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelClt120, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelClt120, 192);
    lv_obj_set_y(ui_LabelClt120, 68);
    lv_obj_set_align(ui_LabelClt120, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelClt120, "120");
    lv_obj_set_style_text_color(ui_LabelClt120, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelClt120, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelClt120, &ui_font_FontIndicatorLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelIat0 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_LabelIat0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIat0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelIat0, 17);
    lv_obj_set_y(ui_LabelIat0, 148);
    lv_obj_set_align(ui_LabelIat0, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelIat0, "0");
    lv_obj_set_style_text_color(ui_LabelIat0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelIat0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelIat0, &ui_font_FontIndicatorLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelIat40 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_LabelIat40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIat40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelIat40, 107);
    lv_obj_set_y(ui_LabelIat40, 148);
    lv_obj_set_align(ui_LabelIat40, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelIat40, "40");
    lv_obj_set_style_text_color(ui_LabelIat40, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelIat40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelIat40, &ui_font_FontIndicatorLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelIat80 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_LabelIat80, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIat80, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelIat80, 197);
    lv_obj_set_y(ui_LabelIat80, 148);
    lv_obj_set_align(ui_LabelIat80, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelIat80, "80");
    lv_obj_set_style_text_color(ui_LabelIat80, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelIat80, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelIat80, &ui_font_FontIndicatorLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelOilTemp120 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_LabelOilTemp120, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOilTemp120, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOilTemp120, 192);
    lv_obj_set_y(ui_LabelOilTemp120, 228);
    lv_obj_set_align(ui_LabelOilTemp120, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelOilTemp120, "120");
    lv_obj_set_style_text_color(ui_LabelOilTemp120, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelOilTemp120, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelOilTemp120, &ui_font_FontIndicatorLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelOilTemp40 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_LabelOilTemp40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOilTemp40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOilTemp40, 17);
    lv_obj_set_y(ui_LabelOilTemp40, 228);
    lv_obj_set_align(ui_LabelOilTemp40, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelOilTemp40, "40");
    lv_obj_set_style_text_color(ui_LabelOilTemp40, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelOilTemp40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelOilTemp40, &ui_font_FontIndicatorLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelOilTemp80 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_LabelOilTemp80, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOilTemp80, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOilTemp80, 113);
    lv_obj_set_y(ui_LabelOilTemp80, 228);
    lv_obj_set_align(ui_LabelOilTemp80, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelOilTemp80, "80");
    lv_obj_set_style_text_color(ui_LabelOilTemp80, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelOilTemp80, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelOilTemp80, &ui_font_FontIndicatorLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAfr10 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_LabelAfr10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAfr10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAfr10, -93);
    lv_obj_set_y(ui_LabelAfr10, 109);
    lv_obj_set_align(ui_LabelAfr10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAfr10, "10");
    lv_obj_set_style_text_color(ui_LabelAfr10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAfr10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAfr10, &ui_font_FontIndicatorLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAfr15 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_LabelAfr15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAfr15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAfr15, 3);
    lv_obj_set_y(ui_LabelAfr15, 109);
    lv_obj_set_align(ui_LabelAfr15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAfr15, "15");
    lv_obj_set_style_text_color(ui_LabelAfr15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAfr15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAfr15, &ui_font_FontIndicatorLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAfr20 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_LabelAfr20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAfr20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAfr20, 90);
    lv_obj_set_y(ui_LabelAfr20, 109);
    lv_obj_set_align(ui_LabelAfr20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAfr20, "20");
    lv_obj_set_style_text_color(ui_LabelAfr20, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAfr20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAfr20, &ui_font_FontIndicatorLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMap100 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_LabelMap100, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMap100, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMap100, 87);
    lv_obj_set_y(ui_LabelMap100, 188);
    lv_obj_set_align(ui_LabelMap100, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMap100, "100");
    lv_obj_set_style_text_color(ui_LabelMap100, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMap100, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMap100, &ui_font_FontIndicatorLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMap50 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_LabelMap50, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMap50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMap50, 1);
    lv_obj_set_y(ui_LabelMap50, 188);
    lv_obj_set_align(ui_LabelMap50, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMap50, "50");
    lv_obj_set_style_text_color(ui_LabelMap50, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMap50, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMap50, &ui_font_FontIndicatorLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMap0 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_LabelMap0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMap0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMap0, -95);
    lv_obj_set_y(ui_LabelMap0, 188);
    lv_obj_set_align(ui_LabelMap0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMap0, "0");
    lv_obj_set_style_text_color(ui_LabelMap0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMap0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMap0, &ui_font_FontIndicatorLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelOil0 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_LabelOil0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOil0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOil0, -207);
    lv_obj_set_y(ui_LabelOil0, 68);
    lv_obj_set_align(ui_LabelOil0, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelOil0, "0");
    lv_obj_set_style_text_color(ui_LabelOil0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelOil0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelOil0, &ui_font_FontIndicatorLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelOil25 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_LabelOil25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOil25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOil25, -105);
    lv_obj_set_y(ui_LabelOil25, 68);
    lv_obj_set_align(ui_LabelOil25, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelOil25, "2.5");
    lv_obj_set_style_text_color(ui_LabelOil25, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelOil25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelOil25, &ui_font_FontIndicatorLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelOil5 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_LabelOil5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOil5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOil5, -17);
    lv_obj_set_y(ui_LabelOil5, 68);
    lv_obj_set_align(ui_LabelOil5, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelOil5, "5");
    lv_obj_set_style_text_color(ui_LabelOil5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelOil5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelOil5, &ui_font_FontIndicatorLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFuelP1 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_LabelFuelP1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFuelP1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFuelP1, -212);
    lv_obj_set_y(ui_LabelFuelP1, 148);
    lv_obj_set_align(ui_LabelFuelP1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelFuelP1, "1");
    lv_obj_set_style_text_color(ui_LabelFuelP1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFuelP1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelFuelP1, &ui_font_FontIndicatorLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFuelP3 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_LabelFuelP3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFuelP3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFuelP3, -110);
    lv_obj_set_y(ui_LabelFuelP3, 148);
    lv_obj_set_align(ui_LabelFuelP3, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelFuelP3, "3");
    lv_obj_set_style_text_color(ui_LabelFuelP3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFuelP3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelFuelP3, &ui_font_FontIndicatorLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFuelP5 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_LabelFuelP5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFuelP5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFuelP5, -17);
    lv_obj_set_y(ui_LabelFuelP5, 148);
    lv_obj_set_align(ui_LabelFuelP5, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelFuelP5, "5");
    lv_obj_set_style_text_color(ui_LabelFuelP5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFuelP5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelFuelP5, &ui_font_FontIndicatorLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFuelLevelF = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_LabelFuelLevelF, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFuelLevelF, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFuelLevelF, -16);
    lv_obj_set_y(ui_LabelFuelLevelF, 228);
    lv_obj_set_align(ui_LabelFuelLevelF, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelFuelLevelF, "f");
    lv_obj_set_style_text_color(ui_LabelFuelLevelF, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFuelLevelF, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelFuelLevelF, &ui_font_FontIndicatorLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFuelLevelH = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_LabelFuelLevelH, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFuelLevelH, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFuelLevelH, -111);
    lv_obj_set_y(ui_LabelFuelLevelH, 228);
    lv_obj_set_align(ui_LabelFuelLevelH, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelFuelLevelH, "h");
    lv_obj_set_style_text_color(ui_LabelFuelLevelH, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFuelLevelH, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelFuelLevelH, &ui_font_FontIndicatorLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFuelLevelE = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_LabelFuelLevelE, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFuelLevelE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFuelLevelE, -207);
    lv_obj_set_y(ui_LabelFuelLevelE, 228);
    lv_obj_set_align(ui_LabelFuelLevelE, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelFuelLevelE, "e");
    lv_obj_set_style_text_color(ui_LabelFuelLevelE, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFuelLevelE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelFuelLevelE, &ui_font_FontIndicatorLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_mainScreen, ui_event_mainScreen, LV_EVENT_ALL, NULL);

}

void ui_mainScreen_screen_destroy(void)
{
    if(ui_mainScreen) lv_obj_del(ui_mainScreen);

    // NULL screen variables
    ui_mainScreen = NULL;
    ui_rpmBar0 = NULL;
    ui_rpmVal0 = NULL;
    ui_rpmLabel1 = NULL;
    ui_speedVal0 = NULL;
    ui_speedLabel1 = NULL;
    ui_afrBar0 = NULL;
    ui_afrVal0 = NULL;
    ui_cltBar0 = NULL;
    ui_cltVal0 = NULL;
    ui_iatBar0 = NULL;
    ui_iatVal0 = NULL;
    ui_vBattLabel1 = NULL;
    ui_vBattVal0 = NULL;
    ui_mapBar0 = NULL;
    ui_mapVal0 = NULL;
    ui_oilPressBar0 = NULL;
    ui_oilPressVal0 = NULL;
    ui_fuelPressBar0 = NULL;
    ui_fuelPressVal0 = NULL;
    ui_fuelLevelBar0 = NULL;
    ui_fuelLevelVal0 = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;
    ui_Label3 = NULL;
    ui_Label4 = NULL;
    ui_Label5 = NULL;
    ui_Label6 = NULL;
    ui_Label7 = NULL;
    ui_cltLabel1 = NULL;
    ui_iatLabel1 = NULL;
    ui_oilTempLabel1 = NULL;
    ui_oilTempBar0 = NULL;
    ui_oilTempVal1 = NULL;
    ui_oilPressLabel1 = NULL;
    ui_fuelPressLabel1 = NULL;
    ui_fuelLevelLabel1 = NULL;
    ui_afrLabel1 = NULL;
    ui_mapLabel1 = NULL;
    ui_LabelClt40 = NULL;
    ui_LabelClt80 = NULL;
    ui_LabelClt120 = NULL;
    ui_LabelIat0 = NULL;
    ui_LabelIat40 = NULL;
    ui_LabelIat80 = NULL;
    ui_LabelOilTemp120 = NULL;
    ui_LabelOilTemp40 = NULL;
    ui_LabelOilTemp80 = NULL;
    ui_LabelAfr10 = NULL;
    ui_LabelAfr15 = NULL;
    ui_LabelAfr20 = NULL;
    ui_LabelMap100 = NULL;
    ui_LabelMap50 = NULL;
    ui_LabelMap0 = NULL;
    ui_LabelOil0 = NULL;
    ui_LabelOil25 = NULL;
    ui_LabelOil5 = NULL;
    ui_LabelFuelP1 = NULL;
    ui_LabelFuelP3 = NULL;
    ui_LabelFuelP5 = NULL;
    ui_LabelFuelLevelF = NULL;
    ui_LabelFuelLevelH = NULL;
    ui_LabelFuelLevelE = NULL;

}
