// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_mainScreen
extern void ui_mainScreen_screen_init(void);
extern void ui_mainScreen_screen_destroy(void);
extern void ui_event_mainScreen(lv_event_t * e);
extern lv_obj_t * ui_mainScreen;
extern lv_obj_t * ui_rpmBar0;
extern lv_obj_t * ui_rpmVal0;
extern lv_obj_t * ui_rpmLabel1;
extern lv_obj_t * ui_speedVal0;
extern lv_obj_t * ui_speedLabel1;
extern lv_obj_t * ui_afrBar0;
extern lv_obj_t * ui_afrVal0;
extern lv_obj_t * ui_cltBar0;
extern lv_obj_t * ui_cltVal0;
extern lv_obj_t * ui_iatBar0;
extern lv_obj_t * ui_iatVal0;
extern lv_obj_t * ui_vBattLabel1;
extern lv_obj_t * ui_vBattVal0;
extern lv_obj_t * ui_mapBar0;
extern lv_obj_t * ui_mapVal0;
extern lv_obj_t * ui_oilPressBar0;
extern lv_obj_t * ui_oilPressVal0;
extern lv_obj_t * ui_fuelPressBar0;
extern lv_obj_t * ui_fuelPressVal0;
extern lv_obj_t * ui_fuelLevelBar0;
extern lv_obj_t * ui_fuelLevelVal0;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_cltLabel1;
extern lv_obj_t * ui_iatLabel1;
extern lv_obj_t * ui_oilTempLabel1;
extern lv_obj_t * ui_oilTempBar0;
extern lv_obj_t * ui_oilTempVal1;
extern lv_obj_t * ui_oilPressLabel1;
extern lv_obj_t * ui_fuelPressLabel1;
extern lv_obj_t * ui_fuelLevelLabel1;
extern lv_obj_t * ui_afrLabel1;
extern lv_obj_t * ui_mapLabel1;
extern lv_obj_t * ui_LabelClt40;
extern lv_obj_t * ui_LabelClt80;
extern lv_obj_t * ui_LabelClt120;
extern lv_obj_t * ui_LabelIat0;
extern lv_obj_t * ui_LabelIat40;
extern lv_obj_t * ui_LabelIat80;
extern lv_obj_t * ui_LabelOilTemp120;
extern lv_obj_t * ui_LabelOilTemp40;
extern lv_obj_t * ui_LabelOilTemp80;
extern lv_obj_t * ui_LabelAfr10;
extern lv_obj_t * ui_LabelAfr15;
extern lv_obj_t * ui_LabelAfr20;
extern lv_obj_t * ui_LabelMap100;
extern lv_obj_t * ui_LabelMap50;
extern lv_obj_t * ui_LabelMap0;
extern lv_obj_t * ui_LabelOil0;
extern lv_obj_t * ui_LabelOil25;
extern lv_obj_t * ui_LabelOil5;
extern lv_obj_t * ui_LabelFuelP1;
extern lv_obj_t * ui_LabelFuelP3;
extern lv_obj_t * ui_LabelFuelP5;
extern lv_obj_t * ui_LabelFuelLevelF;
extern lv_obj_t * ui_LabelFuelLevelH;
extern lv_obj_t * ui_LabelFuelLevelE;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

