// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_SETTINGSSCREEN_H
#define UI_SETTINGSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_settingsScreen
extern void ui_settingsScreen_screen_init(void);
extern void ui_settingsScreen_screen_destroy(void);
extern void ui_event_settingsScreen(lv_event_t * e);
extern lv_obj_t * ui_settingsScreen;
extern lv_obj_t * ui_labelSettingsScreen;
extern lv_obj_t * ui_rpmWarnContainer;
extern void ui_event_rpmWarnButtonPlus(lv_event_t * e);
extern lv_obj_t * ui_rpmWarnButtonPlus;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_rpmWarnVal;
extern lv_obj_t * ui_rpmWarningLabel;
extern void ui_event_rpmWarnButtonMinus(lv_event_t * e);
extern lv_obj_t * ui_rpmWarnButtonMinus;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_cltWarnContainer;
extern void ui_event_cltWarnButtonPlus(lv_event_t * e);
extern lv_obj_t * ui_cltWarnButtonPlus;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_cltWarnVal;
extern void ui_event_cltWarnButtonMinus(lv_event_t * e);
extern lv_obj_t * ui_cltWarnButtonMinus;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_cltWarningLabel;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_iatWarnContainer;
extern void ui_event_iatWarnButtonPlus(lv_event_t * e);
extern lv_obj_t * ui_iatWarnButtonPlus;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_iatWarnVal;
extern void ui_event_iatWarnButtonMinus(lv_event_t * e);
extern lv_obj_t * ui_iatWarnButtonMinus;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_iatWarningLabel;
extern lv_obj_t * ui_oilTWarnContainer;
extern void ui_event_oilTWarnButtonPlus(lv_event_t * e);
extern lv_obj_t * ui_oilTWarnButtonPlus;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_oilTWarnVal;
extern void ui_event_oilTWarnButtonMinus(lv_event_t * e);
extern lv_obj_t * ui_oilTWarnButtonMinus;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_oilTWarningLabel;
extern lv_obj_t * ui_oilPWarnContainer;
extern void ui_event_oilPWarnButtonPlus(lv_event_t * e);
extern lv_obj_t * ui_oilPWarnButtonPlus;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_oilPWarnVal;
extern void ui_event_oilPWarnButtonMinus(lv_event_t * e);
extern lv_obj_t * ui_oilPWarnButtonMinus;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_oilPWarningLabel;
extern lv_obj_t * ui_fuelPWarnContainer;
extern void ui_event_fuelPWarnButtonPlus(lv_event_t * e);
extern lv_obj_t * ui_fuelPWarnButtonPlus;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_fuelPWarnVal;
extern void ui_event_fuelPWarnButtonMinus(lv_event_t * e);
extern lv_obj_t * ui_fuelPWarnButtonMinus;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_fuelPWarningLabel;
extern lv_obj_t * ui_vBattWarnContainer;
extern void ui_event_vBattWarnButtonPlus(lv_event_t * e);
extern lv_obj_t * ui_vBattWarnButtonPlus;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_vBattWarnVal;
extern void ui_event_vBattWarnButtonMinus(lv_event_t * e);
extern lv_obj_t * ui_vBattWarnButtonMinus;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_vBattWarningLabel;
extern lv_obj_t * ui_turboMapLabel;
extern lv_obj_t * ui_Switch1;
extern void ui_event_saveButton(lv_event_t * e);
extern lv_obj_t * ui_saveButton;
extern lv_obj_t * ui_Label29;
extern void ui_event_defaultWarnSettingsButton(lv_event_t * e);
extern lv_obj_t * ui_defaultWarnSettingsButton;
extern lv_obj_t * ui_Label30;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

